### ISSUE TITLE
Revision General

### ISSUE THREAD

**Issue by agileontheweb** [rockandror/rockandror#15]
* [x] Cambiar teléfono por +0034 607 320 876
* [x] Actualizar el portfolio
  * [x]  Nuevos screenshot de webdings. Actualizar enlace a www.webding.es.
* [x] Correción de textos
  * Síguenos en las redes sociales

**Comment by agileontheweb** [comment]
@Senen ...listo...
en el teléfono puse solo +34 y no +0034, creo que o se pone 00 o +

**Comment by Senen** [comment]
Hecho en Master :-1:
