### ISSUE TITLE
Contact greetings

### ISSUE THREAD

**Issue by Senen** [rockandror/rockandror#23]
Errores:
- [x] Revisar las versiones responsive. El texto en versiones tablet queda mal. Adjunto screenshot
- [x] Eliminar el botón vacio que sale al lado de compartir.
- [x] Añadir social

- [ ] Add tag rails into  %meta{:content => "AÑADIR IMAGE PARA SOCIAL", :property => "og:image"}/
la Imagen esta "app/assets/images/svg/image-share-social.svg"
he intentado tambien asi
#{root_url()}assets/images/svg/image-share-social.svg
no consigo que se vea.
** he conseguido pintar el link pero hay que probarlo online. Seria buena idea mover en AMAZON AWS la image...preguntar a Senen.

![captura de pantalla 2016-07-19 a las 20 50 40](https://cloud.githubusercontent.com/assets/15726/16962591/99f3afae-4df2-11e6-9167-25e8a1737b7e.png)

**Comment by agileontheweb** [comment]
![captura de pantalla 2017-02-22 a las 11 02 28](https://cloud.githubusercontent.com/assets/1497150/23206645/b1cc7302-f8ee-11e6-92a9-54a3304070a2.png)

**Comment by agileontheweb** [comment]
Una vez hecho el merge de esta rama, hay que incluir en el tag 
%meta{:content => "AÑADIR IMAGE PARA SOCIAL", :property => "og:image"}/
la imagen nueva de la home : https://github.com/rockandror/rockandror/pull/45
Ahora mismo al compartir sale esta imagen...
![captura de pantalla 2017-02-22 a las 11 08 16](https://cloud.githubusercontent.com/assets/1497150/23206782/48e02888-f8ef-11e6-8efa-072a17e8d86a.png)

**Comment by agileontheweb** [comment]
Estoy utilizando este para ver como se ve...
https://developers.facebook.com/tools/debug/sharing/?q=rockandror.com

Ahora mismo no puedo hacer la prueba de verdad porque estoy en local.

**Comment by agileontheweb** [comment]
El botón de facebook ya lo puse en el layout nuevo 2018 solo hay que comprobar que online funcione bien tambien para el tema de turbolinks. Cierro la issue porque no sirve.
