### ISSUE TITLE
Home intro animation

### ISSUE THREAD

**Issue by Senen** [rockandror/rockandror#24]
Abtenerse de hacer animaciones si no se terminan correctamente.

* [x] El botón de "Más sobre Rock&Ror" en firefox se ve fatal

Las animaciones siguen siendo complejas de realizar compatibles con todos los navegadores. Recomiendo no hacerlas o después de hacerlas tener la decencia de probarlas en todos los dispositivos.

**Comment by agileontheweb** [comment]
Hola @Senen ya se que tenia que hacer estos cambio en esta rama, pero lo hice en otra 👎 !
En esta rama hay los cambios
https://github.com/rockandror/rockandror/issues/28
Sorry
