### ISSUE TITLE
Mobile version

### ISSUE THREAD

**Issue by Senen** [rockandror/rockandror#25]
No existe manera de llegar a la página de contacto cuando la versión es mobile o tabl.

Creo que debería existir la forma de llegar.

¿Qué opináis?

**Comment by agileontheweb** [comment]
Hola @Senen 
si estos cambio siempre se encuentran en la rama
https://github.com/rockandror/rockandror/issues/28

Cuando haces scroll salgon 3 botones ariba , uno verde uno azul y el menu.
El menu llamar no funciona con el browser normal, hay que utilizar lo smartphone porque hace ya la llamada sin que el usuario tenga que escribir el numero. El boton azul va a la pagina de contacto. El menu abre la modal.
Abierto a cualquier sugerencia.
Yo improvise y me parece buena idea, solo el menu en el medio no me convence mucho.

Puede cerrar esta rama gracias.
