### ISSUE TITLE
Facebook share

### ISSUE THREAD

**Issue by Senen** [rockandror/rockandror#26]
Adjunto pantallazo de la preview de la compartición de Facebook. Parece un poco pobre, creo que puede mejorar bastante con el logo y algún texto.
- [ ] Incluir logo
- [ ] Incluir intro title

![captura de pantalla 2016-07-19 a las 21 30 45](https://cloud.githubusercontent.com/assets/15726/16963731/31f5963c-4df8-11e6-8d23-28e21cffb07b.png)

**Comment by agileontheweb** [comment]
Mirar la https://github.com/rockandror/rockandror/issues/23
Ya tiene todo.
