### ISSUE TITLE
Version Stable

### ISSUE THREAD

**Issue by agileontheweb** [rockandror/rockandror#35]
- [x] Remove autoscroll

**Comment by agileontheweb** [comment]
hola @Senen  @taitus,  este fin de semana me he pegado una buena encarni por nuestra web.
Hago un resumen y si teneis tiempo para darle un vistazo y decirme si encontrais erorres.

- Anyadido la secion boatjump ( hare una tarea para los texto y la imagenes)
- Refactor sass con mixing y variables foundation  ( aun falta algo )
- Refactor js (Creato funcionalidades separadas y refactorizado el codigo tweenmax)
- Arreglado algunos fallos de diseno
- Hecho mas pequena la bara de navigacion
- Arregaldo el carousel dentro del navbar en modalidad responsive (aun falta en ipad portrait)
- Creado pequena animacion logo
- Creado mejora en la animacion de la intro 
- Testeado en la mayoria de los dispositivos: ipad-iphone 4 5 6 6s etc, mio movil
 - Chrome, Safari, Furefox, Opera
- Todas la version de responsive

He encontrado solo un error en el menu en una version responsive que arreglare en una nueva tarea.
Podemos hacer una tarea con , texto, imagenes, y bug durante esta semana cosi acabamos.
Hai mejoras que hacer, por ejemplo en home page si utilizas un iphone 6s se queda con mucha altura y moleria arreglarlo para que quede mejor, de todas forma  voy escribiendo en una nueva tarea.

La rama en question es:
https://github.com/rockandror/rockandror/tree/greensock-menu

Y tambien es Able to merge.
salut..

**Comment by taitus** [comment]
@agileontheweb  Muy bien Alessandro!!!... yo este finde con la despedida poca cosa. Pero ya estoy por la oficina para partirlo!!!
Luego le pegamos un vistazo a la rama.
