### ISSUE TITLE
Polo

### ISSUE THREAD

**Issue by agileontheweb** [rockandror/rockandror#37]
@Senen @taitus 
Mismo para Rocken.
Polo front y back.
Algo muy simple. Segun donde imprimimos tengo que preguntar la medida para el logo.
De toda forma con el boceto es mas facil ir a preguntar.

![polo-white-rockandror-2](https://cloud.githubusercontent.com/assets/1497150/18253803/4ea227b4-7387-11e6-93ed-dc6da890d677.jpg)
![polo-white-rockandror-1](https://cloud.githubusercontent.com/assets/1497150/18253802/4ea17e4a-7387-11e6-874a-6d12d448e206.jpg)
![polo-grey-rockandror-2](https://cloud.githubusercontent.com/assets/1497150/18253804/4ea35e90-7387-11e6-9167-d246724b4d33.jpg)
![polo-grey-rockandror-1](https://cloud.githubusercontent.com/assets/1497150/18253805/4ea52694-7387-11e6-8163-be1616e7ae09.jpg)

**Comment by taitus** [comment]
@Senen @agileontheweb Visualizo los polos de webdings con el logo y el texto en la parte frontal de webdings... y no se si es mezclar mucho, pero veo en la parte de atras en el cuello en pequeño el logo de rockandror

**Comment by agileontheweb** [comment]
En Drive > Proyectos proprios > Rockandror > Polo
Hay la misma imagenes.
