### ISSUE TITLE
Mockup blog

### ISSUE THREAD

**Issue by agileontheweb** [rockandror/rockandror#40]
- [ ]  Design mockup blog - desktop, Ipad, Iphone.

**Comment by agileontheweb** [comment]
@Senen @taitus 
voy poniendo bocetos..
![boceto_1](https://cloud.githubusercontent.com/assets/1497150/19043473/d1fc9564-897f-11e6-944d-f5a7652896c0.jpg)

**Comment by agileontheweb** [comment]
@Senen @taitus 
layout 2....
![boceto-2](https://cloud.githubusercontent.com/assets/1497150/19044002/ffdc1d9a-8981-11e6-87cf-64508ec15e4d.jpg)

**Comment by agileontheweb** [comment]
@Senen @taitus ....unos mas...
![boceto-3](https://cloud.githubusercontent.com/assets/1497150/19044363/703bcb16-8983-11e6-8619-930a0b9a7f1e.jpg)

**Comment by Senen** [comment]
Cada vez mejor! Yo no me complicaría más.. Tengo ganas de ver el show de post 

Recuerda que seguramente cuando posteemos artículos estos contendrán código, hay que conseguir que se visualize precioso el códido de nuestros posts.

**Comment by agileontheweb** [comment]
@Senen @taitus 
ultimo...y estamos todos de acuerdo ...ya estoy con el show...

**Comment by agileontheweb** [comment]
Unico cambio el icono chat de color gris
![boceto-4](https://cloud.githubusercontent.com/assets/1497150/19044556/6510eeaa-8984-11e6-9aa7-f9c441ebf64c.jpg)

**Comment by agileontheweb** [comment]
@Senen @taitus 
show del blog
![blog-show](https://cloud.githubusercontent.com/assets/1497150/19076491/82dd4442-8a38-11e6-8b46-29be9736d853.jpg)
