### ISSUE TITLE
Mockup 2018

### ISSUE THREAD

**Issue by agileontheweb** [rockandror/rockandror#53]
@Senen , @taitus 
En esta tarea propongo que cada uno aporte opiniones sobre los cambios de nuestra web.
Estos son los layout que tenemos que revisar, no están acabados al 100% , pero creo que ya si la estructura va bien podemos pensar de empezar a maquetar algunas parte, y hacer en un segundo momento los ajuste del texto.

En cada sección hay una idea/boceto de texto, claro hay que acabar el texto en todas las paginas, lo que puse es para tener una idea general.
No miráis si hay más padding o menos margin o el texto no es alineado perfectamente, durante el montaje lo serán.
Al final de la tarea podeis ver los Mockups y los links a Drive para que cada uno pueda aportar texto de cada sección.

Home page
==
Breve descripción.
- Cada sección tiene la altura de la pantalla.
- Cuando hago scroll, scrollea directamente a la sección siguiente - Esta issue la haria al final de todos.
- En responsive la mayoría de las Imágenes desaparecen
- Añadiría en el Navbar el botón equipo, y en el futuro servicios.
- Cada sección tiene su botón para llevar el usuario a cada pagina también para hacer un poco de Seo.
- El navbar de momento no lo tocaria, como tiene en responsive la animación.

Herramientas para el desarrollo web
==
Escribir texto.
Añadir algunas imagen
Añadir enlace a pagina interna y externa

Codigo abierto - participaciones
==
Escribir texto.
Añadir algunas imagen
Añadir enlace a pagina interna y externa

Principio metodologia agil
==
Escribir texto.
Añadir algunas imagen
Añadir enlace a pagina interna y externa

Perfil
==
Hacer fotos nueva perfil.
Escribir un texto general.
Escribir un breve texto sobre lo que cada uno hice antes de Rockandror.

Trabajos
==
Caja gris con logo, en hover la caja coge el color primario de cada cliente con una foto y un pequeño texto.

Show Trabajo
==
Escribir texto.
Cambiar estilo imagen.
El texto creo que debería ser escrito  como un  "Case Study", tambien si en algunos casos no lo son, el caso Boatjump es lo más interesante como sabemos. En este caso puse un link a lanzadera y un articulo de lavanguardia para dar mas importancia a la empresa.

Testimonials
==
Pedir foto.
Pedir texto.
Ya existe una tarea.
https://github.com/rockandror/rockandror/issues/47

Seo - Enlace con las paginas
==

**Home page**
- Herramientas para el desarrollo web
- Principios desarrollo agile
- Participaciones código abierto
- Equipo Rockandror
- Nuestro trabajos
- Contatos

En cada pagina añadir en el texto del contenido algunos links a otras pagina interna y tambien externa.

**Herramientas para el desarrollo web**
- Principios desarrollo agile
- Links a web echas en Rails
- Links a trabajos

**Principios desarrollo agile**
- Participaciones código abierto
- Links a trabajos

**Participaciones código abierto**
- Principios desarrollo agile
- Links a trabajo

**Equipo Rockandror**
- Herramientas para el desarrollo web
- Principios desarrollo agile
- Participaciones y código abierto
- Nuestro trabajos
- Red social  + GitHub de cada persona

**Footer**
- Email
- Link red sociales
- Desarrollo web palma de mallorca - Echa en espera  de revision
- Startup - rama page-startup-43  Echa en espera de revision
- Freepick - Añadir una pagina para meter los links de las imagen que utilizamos de Freepick. - ver carpeta material

En cada pagina al final del contenido ponemos un partial como es ahora nuestra web para ir a la pagina contacto.

Feature
==
Añadir chat estilo zopim? https://crisp.chat/en/livechat/?ref=chatbox&domain=cantierecreativo.net&name=Cantiere%20Creativo

ScreenShot
==
**Home page**
![home](https://user-images.githubusercontent.com/1497150/31270186-950b580e-aa83-11e7-83df-9c4aff3703eb.jpg)

**Herramientas para el desarrollo web**
![herramientas](https://user-images.githubusercontent.com/1497150/31270205-a441b3c2-aa83-11e7-9a06-01e4a8b73513.jpg)

**Desarrollo agil**
![principios-desarrollo-agile](https://user-images.githubusercontent.com/1497150/31270386-8008f35c-aa84-11e7-9f26-8ef2a9ddd6d8.jpg)

**Codigo abierto - participaciones**
![participaciones-codigo-abierto](https://user-images.githubusercontent.com/1497150/31270439-ac11d518-aa84-11e7-817c-41dafca30fc3.jpg)

**Equipo**
![equipo](https://user-images.githubusercontent.com/1497150/31270409-8c50207c-aa84-11e7-9757-603c38bf5e94.jpg)

**Trabajos**
![trabajos](https://user-images.githubusercontent.com/1497150/31270417-971d7194-aa84-11e7-93c0-7ace19b02a09.jpg)

**Trabajo Show - boatjump**
![show-trabajo](https://user-images.githubusercontent.com/1497150/31270456-bb7aa700-aa84-11e7-8235-c848589821d3.jpg)

Drive Texto cada sección
==
**Codigo abierto - partecipaciones**
https://drive.google.com/open?id=1URuUiyRa6iFSNrSKR0FRQQpMEy0ZTqoLT4IJx032izw

**Desarrollo agil**
https://drive.google.com/open?id=1cINtKqyFunjC6U3bMy2JmfOFGpsgIkkVXpRB0GD71B4

**Equipo**
https://drive.google.com/open?id=1vaV-Mm0939dVLD71qUThU3KvQPGkVFfa1EaJWKN7lqQ

**Herramientas**
https://drive.google.com/open?id=1s2bMqLpS5yESBaqFZYTvUn7z4vHg03lIPfY3qVAOV_4

**Trabajos**
https://drive.google.com/open?id=15opV-DIRtPZmvkYF86SdP5zEiX_sfepfdXWmvOrapL4

**Trabajo Show Boatjump**
https://drive.google.com/open?id=10x3UfizMm-fEOD_5Gvw5B8nziwjixyeYZi7CtsJjD5c

==

Personalmente no lo veo muy complicado, creo que el montaje es bastante rapido, con menos fotos y cositas rara solo falta trabajar el texto de todas la pagina y del show de cada cliente, has dicho nada :-) . 
Espero vuestras impresiones sobre los colores o imagen que no ve gustan absolutamente nada, o cualquier cosa.
Gracias

He creado un projecto:
https://github.com/rockandror/rockandror/projects/1

**Comment by Senen** [comment]
Buenísimo trabajo Alle! En cuanto pueda me meto y lo miro todo con más profundidad.

**Comment by agileontheweb** [comment]
Cierro esta issue, ya esta todo montado en html. Los texto se pueden cambiar en cada archivo yml. Los documentos que hacen referencia a Drive ya no sirven.
