### ISSUE TITLE
Ready to put it online

### ISSUE THREAD

**Issue by agileontheweb** [rockandror/rockandror#55]
This branch is: https://github.com/rockandror/rockandror/tree/ready-to-put-it-online

This is a reduced version of the our website, i remove some parts of website for put this online.
This issue comes from https://github.com/rockandror/rockandror/tree/convert-to-bootstrap

**Things removed**
- Removed partial of testimonials from each work.
- Removed testimonials from home page 

**Things to do**
- Check texts in whole web site.
- Check images in whole web site and change or remove if necessary. Add video if necessary. 
- Changed team image.
- Add sitemap.
- Check if facebook ilike button work because i can't test it in localhost. Test if turbolinks work with the button.

**Comment by Senen** [comment]
![captura de pantalla 2018-05-31 a las 19 30 00](https://user-images.githubusercontent.com/15726/40797716-758afd68-6509-11e8-9d87-9077290ab7f0.png)

@agileontheweb esta imagen contiene un error de ortografía. Objectivo =>Objetivo
